version: "3"
services:
  pruebasupermercado:
    build: pruebasupermercado
    mem_limit: 1024m
    ports:
      - "8081:8080"
    environment:
      - DB_URL=jdbc:mysql://pruebasupermercado1:3306/pruebasupermercado?createDatabaseIfNotExist=true&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=123456789
    restart: always
    depends_on:
      pruebasupermercado1:
        condition: service_healthy

  pruebasupermercado1:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=pruebasupermercado
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456789" ]
      interval: 10s
      timeout: 10s
      retries: 10
